### ISSUE TITLE
No WiFi access point created after starting in config mode

### ISSUE THREAD

**Issue by terrag42** [nnaumenko/webconfig-ESP8266-tempmon#1]
Hello, I am having trouble seeing the SSID that the ESP is supposed to create when starting in config mode. For testing, the only sensor I have connected is a DHT11, no MQ-2 or DS18B20.

Here's what my serial monitor reports after I reset the ESP:

Init started.
Chip ID: 16575886
Flash chip ID:1261807
[47] Config loaded from EEPROM.
Config Mode enabled.
Access point created: 
SSID: ESP8266-16575886
Password: ESP1261807
IP address: 0.0.0.0
Web server started.
Init completed.
[2774] sensor values: DHT T = 21.00 RH = 36.00 OneWire(0) T = 0.00 MQ2 AI = 1024.00
[5273] sensor values: DHT T = 21.00 RH = 36.00 OneWire(0) T = 0.00 MQ2 AI = 1024.00 .....

Is there something I can do to make the new access point show up?

**Comment by terrag42** [comment]
Never mind, the access point was created just fine after power cycling a few times. Thank you.

**Comment by nnaumenko** [comment]
Hello, 

It seems that there was an [issue with WiFi.softAP function](https://github.com/esp8266/Arduino/issues/1141) in ESP8266 core for Arduino. If the problem persists please make sure you have the corresponding version of ESP8266 libraries. 

You may also add the following line after Serial.begin:
`Serial.setDebugOutput(true);`
This will enable [diagnostic output](https://github.com/esp8266/Arduino/blob/master/doc/reference.md#serial) from WiFi libraries.

Regards,
Nick
